### PR TITLE
hey man, whats up man

### PR DESCRIPTION
**Pull request by btmclive**
I yapped for a bit, will need to change later

### CODE REVIEW

**Comment by uwukia** [comment]
I disagree with this pull request

**Comment by Utiba** [comment]
this request sucks fuck you

**Comment by ascenttree** [comment]
epic

**Comment by crs100** [comment]
i think you fell off

**Comment by zEduhi** [comment]
i still losing the game, i dont like it

**Comment by flapczek** [comment]
true

**Comment by ZnxTech** [comment]
PLAY GREGTECH

**Review by xen-000 — APPROVED** [review]
yuh

**Comment by Marotzu** [comment]
declining this one
sorry

**Review by NoelleTGS — APPROVED** [review]

**Comment by L-Mario564** [comment]
> yuh

@xen-000 nuh uh

**Review by L1teD — APPROVED** [review]
gud

**Comment by Furthir** [comment]
I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it https://github.com/sherlock-project/sherlock#installation WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

**Review by Utiba — APPROVED** [review]

**Comment by Utiba** [comment]
I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it https://github.com/sherlock-project/sherlock#installation WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

**Comment by zEduhi** [comment]
> I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it https://github.com/sherlock-project/sherlock#installation WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

**Comment by Marotzu** [comment]
I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it https://github.com/sherlock-project/sherlock#installation WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

**Comment by Utiba** [comment]
NOOOOO

**Comment by zEduhi** [comment]
please delete this shit

**Comment by Marotzu** [comment]
fuck it got added

**Comment by windrosu** [comment]
hey GYZE wuss poopin

**Comment by ZnxTech** [comment]
If you see this, You lost the game.

**Pull request merged**
